### ISSUE TITLE
option to have list of image_indices?

### ISSUE THREAD

**Issue by iancharest** [tknapen/nsd_access#3]
https://github.com/tknapen/nsd_access/blob/d0937b800e8c627ffe9e12957f77055c56b28ab1/nsd_access/nsda.py#L333

when fetching the captions for a long list of indices, you end up having to loop through image_indices before calling read_image_coco_info for that current image in the loop, ending up in many i/o to load the captions from memory at each loop iteration. 

could one pass a list of indices (or a single image_index) and return a list of captions (or a single caption)?

**Comment by tknapen** [comment]
I agree. I'll give implementing this a shot, but I'm at a conference now - it'll probably be next week or so, when I'm going to try and give the whole package a push again.
